POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphMiIsImlkIjoiNWRiYjU0ZTljNWFkMzExOWJjYWIwYzI1IiwiaWF0IjoxNTc4MTU5MzY5fQ.DpFWCtqV5I87M8XQqwSWMC0DxDjWTI75lY3qWyYlwLc

{
    "title": "testi457893",
    "author": "Toope",
    "url": "www.eskox",
    "likes": 22
}